import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConfigProvider } from "antd";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <AntdRegistry>
          <ConfigProvider
            theme={{
              "token": {
                "colorPrimary": "#61898e",
                "colorInfo": "#61898e",
                "colorSuccess": "#a8d193",
                "colorWarning": "#ceb076",
                "colorError": "#cc6b6d",
                "colorTextBase": "#464646",
                "colorLink": "#73c6c6",
                "sizeStep": 4,
                "borderRadius": 16
              },
              "algorithm": []

            }}
          >
            {children}

          </ConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
